substitutions:
  # ESP ambilight Tv Wohnzimmer
  devicename: "esp32_6"
  upper_devicename: "ESP32 6"
  devicecomment: "Wohnzimmer TV - RGB LED"
  number_leds: "116"
  # TODO : make it possible to set it to 0% - currently this wont work
  boot_brightness: "90%"
  boot_effect: "E1.31"
  rgb_order: GBR

<<: !include common/esp32-lights.yaml
