substitutions:
  # steckdose - Lichterkette
  devicename: "gosund_sp111_7"
  upper_devicename: "Gosund SP111 7"
  devicecomment: "Lichterkette"
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"
  # minimum wattage to mark consumer as active
  consumer_min_wattage: "10"
  # start on reboot
  boot_status: "off"
  boot_button: "button_switch"

<<: !include common/gosund_sp111.yaml
