platform: template
name: "Version"
icon: mdi:tag-outline
# version is already taken internally
# id: version
lambda: |-
      std::string v = id(build_version).state;
      return v.substr(0, v.find(' '));